name: CI wget voyage

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    #- name: Run a multi-line script
      #run: |
        #echo Add other actions to build,
        #echo test, and deploy your project.
    - name: mkdir downloads
      run: mkdir downloads

    - name: wget Dependencies voyage-0.11.0_amd64.tar.gz
      uses: wei/wget@v1
      with:
        args: -O downloads/voyage-0.11.0_amd64.tar.gz https://cloud.3mdeb.com/index.php/s/rUZPwRHOjxpSxN4/download
    - run: gzip -k -v -d downloads/*.tar.gz
    - run: xz -v -e -9 downloads/*.tar
    - name: Release
      uses: softprops/action-gh-release@v1
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          downloads/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

